README.md

*this should fix the broken images within the pypi readme.* you can double check with the following links:
- https://raw.githubusercontent.com/agentops-ai/agentstack/main/logo.svg
- https://raw.githubusercontent.com/agentops-ai/agentstack/main/stack.png
- [Making a PyPI-friendly README - Python Packaging User Guide](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/)
- [python - How do I add images to a PyPI readme (that works on GitHub)? - Stack Overflow](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github)

(bug) fixing image references so that they show up in pypi

---

agentstack/cli/agentstack_data.py
agentstack/cli/cli.py
agentstack/generation/tool_generation.py
agentstack/utils.py

Use the wizard to add tools in project setup

Fix tools wizard

---

agentstack/generation/tool_generation.py
agentstack/utils.py

add tool to agenstack.json

---

agentstack/templates/crewai/tools/agent-connect.py
agentstack/tools/agent-connect.json
agentstack/tools/tools.json

This PR introduces agent-connect, a tool designed to enhance communication capabilities for intelligent agents, allowing them to connect and form collaborative networks. The addition aims to address key challenges faced by intelligent agents, specifically identity verification and encrypted communication.
Agent-connect is based on the Agent Network Protocol, a protocol developed using the W3C DID specifications combined with blockchain and end-to-end encryption. It offers a novel solution for cross-platform identity verification and secure communication among intelligent agents. With agent-connect, each agent can autonomously control its identifiers, authenticate identities, and establish encrypted communication with other agents in a decentralized, scalable manner.
For further …

Add tool：agent-connect, A Tool for Intelligent Agent Communication and Collaboration

---

agentstack/cli/cli.py
agentstack/generation/tool_generation.py
agentstack/tools/browserbase.json
agentstack/tools/firecrawl.json
agentstack/tools/ftp.json
agentstack/tools/mem0.json
agentstack/utils.py

After installing a tool, tool providers can optionally include a call to action instructing the user what to do next
Ex: `Create an API key at https://xxx.xxx/`

add CTA functionality

---

Formula/agentstack.rb

I had some issues with my local python env, so built a homebrew formula.
In general, homebrew allows installation of packages from GitHub with the following format
```
brew install <username>/<repo>
```
However, this requires that we have a repo named github.com/agentops-ai/homebrew-agentstack, with the contents of this PR.
If we want to keep it all in the same repo, users can run the following instead
```
brew tap agentops-ai/agentstack https://github.com/agentops-ai/agentstack
brew install agentops-ai/agentstack/agentstack
```
In order for this to work, we need to ensure that every dep from the lockfile is codified in the formula, and that the url + shasum are kept up to date for each release.
In the formula, you'll see "url" and "shasum". Those will need updating per release. You'll …

feat: add homebrew Formula

---

agentstack/generation/__init__.py
agentstack/generation/gen_utils.py
agentstack/generation/tool_generation.py
agentstack/main.py
agentstack/tools/agent_connect.json
agentstack/tools/browserbase.json
agentstack/tools/code_interpreter.json
agentstack/tools/composio.json
agentstack/tools/directory_search.json
agentstack/tools/exa.json
agentstack/tools/file_read.json
agentstack/tools/firecrawl.json
agentstack/tools/ftp.json
agentstack/tools/mem0.json
agentstack/tools/open_interpreter.json
agentstack/tools/perplexity.json
agentstack/tools/vision.json

`remove_tool` will delete the tool's py file, remove it from imports and instruct the user to uninstall dependencies. 
It does not delete the `.env` variables, since I thought we might not want to delete user data. 
Verifies that a tool is installed before removing, and verifies it is *not* installed before adding. 
Also removed the code for `add_tool_to_agent_definition` since it looks like that's covered by decorators now.

Implement tool removal command #35

---

agentstack/generation/tool_generation.py
agentstack/tools/~README.md

Also added some basic documentation for the tool JSON format.
This addresses #56

Add post_install and post_remove hooks to tool json configs

---

agentstack/cli/cli.py
agentstack/templates/crewai/{{cookiecutter.project_metadata.project_slug}}/src/main.py
agentstack/utils.py
pyproject.toml
tests/test_generation_files.py
tests/test_project_run.py
tests/test_telemetry.py
tox.ini

Load `<project_dir>/.env` from agentstack `run_project` and pass the environment to a subprocess. Addresses #41 
Disable telemetry in test suite. Add a test for telemetry. #105

Support disabling telemetry with an environment variable, load dotenv on run_project

---

agentstack/update.py
tests/test_update.py
tox.ini

Add `AGENTSTACK_UPDATE_DISABLE` environment variable to disable automatic update checks.

Disable update check in test environment

---

agentstack/agents.py
agentstack/cli/__init__.py
agentstack/cli/cli.py
agentstack/frameworks/__init__.py
agentstack/frameworks/crewai.py
agentstack/generation/agent_generation.py
agentstack/generation/asttools.py
agentstack/generation/files.py
agentstack/main.py
agentstack/proj_templates.py
agentstack/tasks.py
agentstack/utils.py
tests/test_cli_init.py
tests/test_cli_templates.py
tests/test_templates_config.py

`agentstack export <filename>` to export a project to a template. 
`inputs` are not populated, since they are stored in multiple locations in the project's `main.py` file. #122 introduces an `inputs.yaml` file to the project which can be the canonical location for this data. 
Addresses #85

Export agentstack project as a template

---

README.md
agentstack/cli/__init__.py
agentstack/cli/cli.py
agentstack/cli/tools.py
agentstack/frameworks/crewai.py
agentstack/generation/tool_generation.py
agentstack/main.py
agentstack/templates/crewai/{{cookiecutter.project_metadata.project_slug}}/README.md
docs/tools/tools.mdx

Repeatedly add tools to different agents without reinstalling all supporting tools. 
Bugfix: Prevent duplicate tools from being added to the same agent.

Interactively add tools with `agentstack tools add` if no tool_name is passed.

---

agentstack/main.py
agentstack/telemetry.py

Telemetry now stores the result of the command and error messages to better support users
**🧪 Testing**
Tested locally

update telemetry with result and error

---

agentstack/auth.py
agentstack/main.py

Allows the CLI to authenticate with AgentStack.sh

authenticate CLI with agentstack account

---

agentstack/cli/cli.py
agentstack/utils.py
tests/cli_test_utils.py
tests/test_cli_init.py
tests/test_cli_loads.py
tests/test_cli_templates.py
tests/test_cli_tools.py
tests/test_utils.py

When scaffolding the agents and tasks, empty agent or task name [resulted in an exception as documented in this open issue](https://github.com/AgentOps-AI/AgentStack/issues/142).
Improved text inputs with validations.
Simplified code.
**🧪 Testing**
Initialized a new agent and entered invalid values.

BUGFIX-142

---

agentstack/generation/files.py
agentstack/tools/agent_connect.json
agentstack/tools/browserbase.json
agentstack/tools/composio.json
agentstack/tools/exa.json
agentstack/tools/firecrawl.json
agentstack/tools/ftp.json
agentstack/tools/mem0.json
agentstack/tools/neon.json
agentstack/tools/perplexity.json
agentstack/tools/stripe.json
tests/fixtures/.env
tests/test_generation_files.py

This prevents us from preferring something like the `OPENAI_API_KEY="..."` definition we add to the project's `.env` file from overriding a valid value that the user has in their `~/.env` file.

Comment out placeholder environment variables

---

agentstack/telemetry.py

If a user is authenticated, include their token in telemetry requests

telem with user token

---

agentstack/cli/cli.py

Currently, if the project init fails on any of these conditions, it continues to attempt to create the project and fails later. We should just exit on the failure.
**🧪 Testing**
locally

exit on init failure

---

agentstack/main.py

Fixes an issue where commands that dont require being in a project still printed the help dialogue

fix help print

---

README.md
tox.ini

We're currently calculating coverage of tests themselves; ignore that directory. 
Add badges to README.

Exclude tests from coverage, add badges to README

---

agentstack/telemetry.py
tox.ini

GitHub CI was currently logging telemetry, this stops that

stop test telemetry logging

---

agentstack/frameworks/crewai.py

We're interacting with a crew project on init, but don't actually have crew installed since the project's venv is not yet active. Defer importing crew until we actually need it. 
This resolves #215

Move crewai tool decorator import to function where it is used to prevent import errors on `init`.

---

agentstack/__init__.py
agentstack/cli/run.py
agentstack/frameworks/__init__.py
agentstack/frameworks/crewai.py
docs/tools/tools.mdx
pyproject.toml

There is currently a major bug in AgentOps wherein tool use is not being captured with Crew agents.
This has proven to be a degradation of AgentStack workflows, so we're implementing a fix here.
> NOTE: this should be reverted once AgentOps fixes the underlying issue
Also some typing and spelling/grammer fixes

Agentops tool fix

---

pyproject.toml

Was getting the following error when I `agentstack init <name>`. 
```
agentstack init example
Traceback (most recent call last):
File "/Users/paolo.delmundo/tmp/agentstack-test/.venv/bin/agentstack", line 5, in
from agentstack.main import main
File "/Users/paolo.delmundo/tmp/agentstack-test/.venv/lib/python3.10/site-packages/agentstack/main.py", line 7, in
from agentstack.cli import (
File "/Users/paolo.delmundo/tmp/agentstack-test/.venv/lib/python3.10/site-packages/agentstack/cli/init.py", line 1, in
from .cli import init_project_builder, configure_default_model, export_template, welcome_message
File "/Users/paolo.delmundo/tmp/agentstack-test/.venv/lib/python3.10/site-packages/agentstack/cli/cli.py", line 22, in
from agentstack.generation.files import ProjectFile
File …
```

add tomli in pyproject.toml

---

agentstack/_tools/neon/config.json
tests/test_tool_config.py

i tested neon after merging which was silly and ran into this:
```
uv: [error]
error: Failed to parse: `neon-api>=0.1.5 psycopg2-binary`
Caused by: Trailing `psycopg2-binary` is not allowed
neon-api>=0.1.5 psycopg2-binary
^^^^^^^^^^^^^^^^^^^^^^^
An error occurred: 
too many values to unpack (expected 2)
```
fixed by adding a version to the dep in tool config
also added a test to check for this in the future

[bug] add version to neon dependency and add check

---

agentstack/packaging.py

Makes the output during `agentstack init` more sensible since we were printing status of the package install, but not which package is being installed.

Add log output indicating that a package is being installed/upgraded/removed

---

agentstack/cli/init.py
agentstack/cli/spinner.py
agentstack/packaging.py
docs/llms.txt

Re-prompt user for project name instead of exiting, spinner for package install

---

.github/workflows/compile-llms-txt.yml

- on pr only
- use workflow git tags instead of commands

fix llm txt workflow

---

.github/workflows/release-checksum.yml

GitHub action for calculating checksums on release.

---

install.sh

Install robustness

---

agentstack/_tools/agentql/__init__.py

This PR adds a new header to the extract_data tool in AgentQL to specify the request origin.
- Add the "X-TF-Request-Origin": "agentstack" header to the headers dictionary

Set X-TF-Request-Origin header in AgentQL tool

---

agentstack/_tools/agentmail/__init__.py
agentstack/_tools/agentmail/config.json
docs/tools/community.mdx
docs/tools/tool/agentmail.mdx

Adding the [AgentMail](https://agentmail.to) tool
**🧪 Testing**
Tested all tools using our agent/tool evaluation suite
Also passed `mox`, `mypy`, and `ruff`

Add AgentMail tool

---

agentstack/_tools/hyperbrowser/__init__.py
agentstack/_tools/hyperbrowser/config.json
docs/tools/community.mdx
docs/tools/tool/hyperbrowser.mdx

Adds these tools from [Hyperbrowser](https://hyperbrowser.ai):
- `scrape_webpage`
- `crawl_website`
- `extract_data_from_webpages`
- `run_browser_use_agent`
- `run_claude_computer_use_agent`
- `run_openai_cua_agent`
**🧪 Testing**
- Add tool to test project
- `$ ruff format agentstack/_tools/hyperbrowser`

Add hyperbrowser tools
