.gitignore
agentstack/cli/cli.py
agentstack/main.py

allow for `agentstack init <slug_name>`

feat: Init with slug name

---

.github/workflows/python-testing.yml
tox.ini

Adds a testing workflow with tox

setup testing

---

.github/workflows/deploy.yml
Formula/agentstack.rb

This PR introduces a github action that generates a homebrew formula to make installing agentstack possible via brew.

homebrew formula gen action

---

agentstack/templates/crewai/tools/perplexity_tool.py
agentstack/tools/perplexity.json
agentstack/tools/tools.json
pyproject.toml

perplexity tool

---

agentstack/generation/gen_utils.py
agentstack/generation/task_generation.py

This PR uses AST to identify the task definition section of crew.py and add new tasks after previous tasks are defined.

Order tasks properly

---

agentstack/templates/crewai/tools/stripe_tool.py
agentstack/tools/stripe.json
agentstack/tools/tools.json

This PR introduces Stripe Agent Tools

Add Stripe tooling

---

README.md
agentstack/cli/cli.py
agentstack/main.py
agentstack/telemetry.py
agentstack/utils.py
pyproject.toml

This PR adds some telemetry so we can better understand how people are using agentstack 
It also adds a new command `agentstack run` that executes the agent depending on the framework you're using

Telemetry and Run

---

agentstack/cli/__init__.py
agentstack/cli/cli.py
agentstack/generation/agent_generation.py
agentstack/generation/files.py
agentstack/main.py
tests/test_generation_files.py

Add selection process for default agent model and save selection to agentstack.json

---

README.md
docs/README.md
docs/contributing/adding-tools.mdx
docs/installation.mdx
docs/mint.json
docs/quickstart.mdx
docs/templates/community.mdx
docs/templates/content_creator.mdx
docs/templates/researcher.mdx
docs/templates/system_analyzer.mdx
docs/templates/templates.mdx

Template Documentation

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/documentation_update.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/integration_request.yaml
.github/ISSUE_TEMPLATE/tool_request.yaml
.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml

Added Github issue templates for OSS contributors 
#94

issue templates

---

.pre-commit-config.yaml
CONTRIBUTING.md
agentstack/cli/agentstack_data.py
agentstack/cli/cli.py
agentstack/generation/agent_generation.py
agentstack/generation/files.py
agentstack/generation/gen_utils.py
agentstack/generation/task_generation.py
agentstack/generation/tool_generation.py
agentstack/main.py
agentstack/utils.py
pyproject.toml
tests/test_cli_loads.py
tests/test_generation_files.py

`pre-commit install` to have `mypy` and `ruff` run before making a commit.
`mypy` passes now.

Run mypy and ruff on pre commit, type checking fixes

---

.github/workflows/mypy.yml

This depends on dependencies added to `pyproject.toml` in #103

Create mypy action

---

agentstack/cli/cli.py
agentstack/generation/files.py
agentstack/templates/crewai/{{cookiecutter.project_metadata.project_slug}}/pyproject.toml
agentstack/utils.py
tests/test_generation_files.py

Do not install project packages in the init process, instead add them as dependencies in the project's pyproject.toml file.

Ensure init and init with --template work as expected.

---

agentstack/cli/agentstack_data.py
agentstack/cli/cli.py
agentstack/proj_templates.py
agentstack/templates/proj_templates/content_creator.json
tests/test_cli_init.py
tests/test_cli_loads.py
tests/test_templates_config.py

Add tests for initializing project from all bundled templates.

Project template validation. 

---

tests/test_cli_init.py
tests/test_cli_tools.py
tox.ini

TODO: When installing tools dependency resolution hangs in test environment.

More CLI test coverage

---

docs/mint.json

Update footer social links to point to AgentStack's X and GitHub
**🧪 Testing**
...

docs: update footer social links to point to AgentStack socials

---

.github/workflows/mintlify-check.yml

Add a github check that mintlify builds successfully on PR

check that mintlify builds successfully

---

.github/workflows/mintlify-check.yml
CONTRIBUTING.md
agentstack/update.py
docs/contributing/adding-tools.mdx
docs/development.mdx

tool add docs

---

.github/workflows/codecov.yml
tests/test_agents_config.py
tests/test_tasks_config.py
tox.ini

Adds codecov to the repo and fixes a couple tests failing with tox while testing

Code Coverage

---

.github/workflows/codecov.yml
.github/workflows/version-check-on-release.yml

adds a github action that verifies the version is correct in pyproject.toml before release

version check action

---

examples/web_researcher/poetry.lock
examples/web_researcher/pyproject.toml

I bumped the version of the Python API SDK to v0.3.0 which fixes some bugs since the SDK was not prepared to work against the latest version of the Neon API.
**🧪 Testing**
https://gist.github.com/davidgomes/0dc62d91dbe6bfc83d2d1a30ea765082

Bumps Neon SDK to v0.3.0 to fix some bugs

---

agentstack/generation/files.py
tests/fixtures/.env
tests/test_generation_files.py

Make .env file parser more robust

---

agentstack/cli/init.py
agentstack/generation/agent_generation.py
agentstack/generation/task_generation.py
agentstack/generation/tool_generation.py

Cleaned up the init messaging and added emoji to the next steps since the output is a bit noisy on first run.

Highlight next `init` steps with emoji.

---

docs/tools/community.mdx
docs/tools/tool/neon.mdx

Added docs page for Neon and a database section + link on the Community Tools page
**🧪 Testing**
Made a sample project akin to web_researcher to validate the content.
@bboynton97 @davidgomes

Add Neon docs

---

agentstack/agents.py
agentstack/frameworks/__init__.py
tests/fixtures/frameworks/crewai/entrypoint_max.py
tests/fixtures/frameworks/langgraph/entrypoint_max.py
tests/test_frameworks.py

Validate that YAML tasks & agents match methods in entrypoint

---

.github/workflows/python-testing.yml
pyproject.toml
tests/test_cli_templates.py
tests/test_cli_tools.py
tests/test_frameworks.py
tests/test_frameworks_langgraph.py
tests/test_generation_agent.py
tests/test_generation_files.py
tests/test_generation_tasks.py
tests/test_generation_tool.py
tests/test_inputs_config.py
tests/test_log.py
tests/test_project_run.py
tests/test_tasks_config.py
tests/test_templates_config.py
tox.ini

Create separate test environments for each framework.

---

agentstack/cli/init.py

fix empty template initialization

---

.github/workflows/compile-llms-txt.yml
agentstack/cli/cli.py
agentstack/frameworks/langgraph.py

Added `deepseek/deepseek-chat` `deepseek/deepseek-reasoner` `deepseek/deepseek-coder` and `groq/deepseek-r1-distill-llama-70b` and fixed `compile_llms_txt` workflow path
**🧪 Testing**
tested with groq 
#247

Add deepseek using groq & deepseek-ai, fixed path for llms.txt workflow

---

.github/workflows/codecov.yml
docs/llms.txt

Codecov is failing because the `tox` run it is configured with is not outputting a `coverage.xml` file.

Fix codecov action

---

agentstack/cli/init.py

Ask the user for a project slug_name on init if none is provided

---

agentstack/_tools/file_read/config.json
docs/tools/tool/file_read.mdx

Fix URL to file_read tool and extend docs

---

agentstack/main.py
docs/llms.txt

Add correct URL to `agentstack templates`

---

agentstack/cli/init.py
agentstack/repo.py
docs/llms.txt
tests/test_repo.py

Disable git if repo exists

---

docs/tools/tool/agentql.mdx

This PR updates the AgentQL page and adds AgentStack examples that uses the AgentQL tool.
**🧪 Testing**
N/A

Update Agentql page

---

agentstack/_tools/agentql/__init__.py

Add a new `stealth_mode` parameter in the AgentQL tool
**🧪 Testing**
Ran the `sentiment_analyser` and `market_monitoring` examples with stealth mode

Add stealth mode in AgentQL tool 
